services:
  backend:
    build:
      context: ../LAB05_ARSW    
      dockerfile: Dockerfile
    ports:
      - '8080:8080'

  frontend:
    build: .
    ports:
      - '5173:4173'
    environment:
      - VITE_API_BASE_URL=http://backend:8080/api
      - VITE_USE_MOCK=false
    depends_on:
      - backend